// Package cartservice_server_rest_server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.1-0.20240604070534-2f0ff757704b DO NOT EDIT.
package cartservice_server_rest_server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	. "github.com/kurtosis-tech/new-obd/src/cartservice/api/http_rest/types"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Add item
	// (POST /cart)
	PostCart(ctx echo.Context) error
	// Empty cart
	// (DELETE /cart/{user_id})
	DeleteCartUserId(ctx echo.Context, userId UserId) error
	// Get cart
	// (GET /cart/{user_id})
	GetCartUserId(ctx echo.Context, userId UserId) error
	// Health check endpoint
	// (GET /health)
	GetHealth(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostCart converts echo context to params.
func (w *ServerInterfaceWrapper) PostCart(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCart(ctx)
	return err
}

// DeleteCartUserId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCartUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCartUserId(ctx, userId)
	return err
}

// GetCartUserId converts echo context to params.
func (w *ServerInterfaceWrapper) GetCartUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCartUserId(ctx, userId)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/cart", wrapper.PostCart)
	router.DELETE(baseURL+"/cart/:user_id", wrapper.DeleteCartUserId)
	router.GET(baseURL+"/cart/:user_id", wrapper.GetCartUserId)
	router.GET(baseURL+"/health", wrapper.GetHealth)

}

type NotOkJSONResponse ResponseInfo

type PostCartRequestObject struct {
	Body *PostCartJSONRequestBody
}

type PostCartResponseObject interface {
	VisitPostCartResponse(w http.ResponseWriter) error
}

type PostCart200JSONResponse map[string]interface{}

func (response PostCart200JSONResponse) VisitPostCartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostCartdefaultJSONResponse struct {
	Body       ResponseInfo
	StatusCode int
}

func (response PostCartdefaultJSONResponse) VisitPostCartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteCartUserIdRequestObject struct {
	UserId UserId `json:"user_id"`
}

type DeleteCartUserIdResponseObject interface {
	VisitDeleteCartUserIdResponse(w http.ResponseWriter) error
}

type DeleteCartUserId200JSONResponse map[string]interface{}

func (response DeleteCartUserId200JSONResponse) VisitDeleteCartUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCartUserIddefaultJSONResponse struct {
	Body       ResponseInfo
	StatusCode int
}

func (response DeleteCartUserIddefaultJSONResponse) VisitDeleteCartUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetCartUserIdRequestObject struct {
	UserId UserId `json:"user_id"`
}

type GetCartUserIdResponseObject interface {
	VisitGetCartUserIdResponse(w http.ResponseWriter) error
}

type GetCartUserId200JSONResponse Cart

func (response GetCartUserId200JSONResponse) VisitGetCartUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCartUserIddefaultJSONResponse struct {
	Body       ResponseInfo
	StatusCode int
}

func (response GetCartUserIddefaultJSONResponse) VisitGetCartUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthdefaultJSONResponse struct {
	Body       ResponseInfo
	StatusCode int
}

func (response GetHealthdefaultJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Add item
	// (POST /cart)
	PostCart(ctx context.Context, request PostCartRequestObject) (PostCartResponseObject, error)
	// Empty cart
	// (DELETE /cart/{user_id})
	DeleteCartUserId(ctx context.Context, request DeleteCartUserIdRequestObject) (DeleteCartUserIdResponseObject, error)
	// Get cart
	// (GET /cart/{user_id})
	GetCartUserId(ctx context.Context, request GetCartUserIdRequestObject) (GetCartUserIdResponseObject, error)
	// Health check endpoint
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostCart operation middleware
func (sh *strictHandler) PostCart(ctx echo.Context) error {
	var request PostCartRequestObject

	var body PostCartJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostCart(ctx.Request().Context(), request.(PostCartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCart")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostCartResponseObject); ok {
		return validResponse.VisitPostCartResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteCartUserId operation middleware
func (sh *strictHandler) DeleteCartUserId(ctx echo.Context, userId UserId) error {
	var request DeleteCartUserIdRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCartUserId(ctx.Request().Context(), request.(DeleteCartUserIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCartUserId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteCartUserIdResponseObject); ok {
		return validResponse.VisitDeleteCartUserIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCartUserId operation middleware
func (sh *strictHandler) GetCartUserId(ctx echo.Context, userId UserId) error {
	var request GetCartUserIdRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCartUserId(ctx.Request().Context(), request.(GetCartUserIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCartUserId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCartUserIdResponseObject); ok {
		return validResponse.VisitGetCartUserIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx echo.Context) error {
	var request GetHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Request().Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		return validResponse.VisitGetHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RV34sbNxD+V8S0kBfZu/UVSvft2lyvpnB3+O4oNBxBlca2Eq+kk0Yhxuz/XiStY6+9",
	"adKftLAPWmk08803M592IG3rrEFDAZodOOFFi4Q+/8WA/rVWaakwSK8daWugyQdMK+Cg068TtAYORrTY",
	"H77Ohx6fo/aooCEfkUOQa2xFckdbl0wDeW1W0HVdMg7OmoA58o2l27dpIa0hNJSWwrmNliJBqN6EhGN3",
	"5PFLj0to4IvqkFBVTkO16F3PzdKWYMN0Hg2+dygJFUPvrYdk0l9Ovi+VmhO2C3yOGDIW561DT7qg1YTt",
	"pzB8LzwlJ9DxY15PieD7HfvrG5SUrNPN8ZjDxedG7wMI78X2z6GZ9/kOETlvVZQ07orDcxSGNG3T4dL6",
	"VhA0oA1dzOBDGG0IV+jHI/+IYkPrfS3P4wcSFPMK34vWbdLtx7uD8wMU0i0GEq0bGs/q2deT+pvJ7NuH",
	"um7y9wvwA1glCCfp7rnPMbyDrjtDK63CARXxY1xwaDEEscJRWsvG5/X/Q7Its7YfzFfFwSEGL8iefieh",
	"hz4kmtgmD1eLxe0COMxvfrgFDj9fLm7mN9dHLo7HXPdsDCdwcXX/sIwbdnk3Z8Gh1Mt+0tnSekZrZKnv",
	"WED/TkvkTNOLwGJAxcgyEclOVmjQC0ImNxoNsfuXP70ITBiVL6GfBK2Q5dxSA1Cu+LFT4PAOfSh46ulX",
	"0zrlbB0a4TQ0cDGtpxfAs9jlClZyP5i2iEIqbwY9V9DAnQ2UR7fQjYG+s2r7t2naiSZ1w7ImvT3V1Fld",
	"/6HoJ/U/l837KCWGkOq2DwTZaCnihj6WwAdMVRH5rLWxbYXfQpOklmU5TduZ4WrXC1RX2maDhOdsv8z7",
	"ie/HgH6ucqEOb9mrcSwHk2qvgt3T/5G2q9bRluWG7DiscKQfr5H+C/R86pX6txi7Rur5So22zm9L8tRz",
	"dyJPSNGbkIWomLLy2jC7zJu9hkyBn7Ne3i34B3k7eRnHGCz4mA49/u1fJrAEZXKN8i1Do5zVpq9eUdzS",
	"V0Mcx4KbxB44RL+BBtZELjRVnvi9IHdP3W8BAAD//7SS+pagCgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
