// Package cartservice_rest_types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.1-0.20240604070534-2f0ff757704b DO NOT EDIT.
package cartservice_rest_types

import (
	"time"
)

// Defines values for ResponseType.
const (
	ERROR   ResponseType = "ERROR"
	INFO    ResponseType = "INFO"
	WARNING ResponseType = "WARNING"
)

// AddItemRequest defines model for AddItemRequest.
type AddItemRequest struct {
	Item   *CartItem `json:"item,omitempty"`
	UserId *string   `json:"user_id,omitempty"`
}

// Cart defines model for Cart.
type Cart struct {
	Items  *[]CartItem `json:"items,omitempty"`
	UserId *string     `json:"user_id,omitempty"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	ProductId *string `json:"product_id,omitempty"`
	Quantity  *int32  `json:"quantity,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status    *string    `json:"status,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// ResponseInfo defines model for ResponseInfo.
type ResponseInfo struct {
	Code    uint32       `json:"code"`
	Message string       `json:"message"`
	Type    ResponseType `json:"type"`
}

// ResponseType defines model for ResponseType.
type ResponseType string

// UserId defines model for user_id.
type UserId = string

// NotOk defines model for NotOk.
type NotOk = ResponseInfo

// PostCartJSONRequestBody defines body for PostCart for application/json ContentType.
type PostCartJSONRequestBody = AddItemRequest
