// Package productcatalogservice_rest_types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.1-0.20240604070534-2f0ff757704b DO NOT EDIT.
package productcatalogservice_rest_types

import (
	"time"
)

// Defines values for ResponseType.
const (
	ERROR   ResponseType = "ERROR"
	INFO    ResponseType = "INFO"
	WARNING ResponseType = "WARNING"
)

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status    *string    `json:"status,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Money defines model for Money.
type Money struct {
	CurrencyCode *string `json:"currency_code,omitempty"`
	Nanos        *int32  `json:"nanos,omitempty"`
	Units        *int64  `json:"units,omitempty"`
}

// Product defines model for Product.
type Product struct {
	Categories  *[]string `json:"categories,omitempty"`
	Description *string   `json:"description,omitempty"`
	Id          *string   `json:"id,omitempty"`
	Name        *string   `json:"name,omitempty"`
	Picture     *string   `json:"picture,omitempty"`
	PriceUsd    *Money    `json:"price_usd,omitempty"`
}

// ResponseInfo defines model for ResponseInfo.
type ResponseInfo struct {
	Code    uint32       `json:"code"`
	Message string       `json:"message"`
	Type    ResponseType `json:"type"`
}

// ResponseType defines model for ResponseType.
type ResponseType string

// Id defines model for id.
type Id = string

// NotOk defines model for NotOk.
type NotOk = ResponseInfo
