apiVersion: v1
kind: Service
metadata:
  name: voting-app-ui-external
  annotations:
    kardinal.dev.service/ingress: "true"
    kardinal.dev.service/host: "prod.app.localhost"
spec:
  type: LoadBalancer
  selector:
    app: voting-app-ui
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      appProtocol: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-ui
  labels:
    app: voting-app-ui
    version: v1
  namespace: voting-app
  annotations:
    kardinal.dev.service/plugins: |
      - name: github.com/kurtosis-tech/neondb-plugin
        type: external
        servicename: neon-postgres-db
        args:
          NEON_API_KEY: ""
          NEON_PROJECT_ID: """
          NEON_FORK_FROM_BRANCH_ID: """
spec:
  type: ClusterIP
  selector:
    app: voting-app-ui
  ports:
    - name: http
      port: 80
      protocol: TCP
      appProtocol: HTTP 
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: voting-app-ui
    version: v1
  name: voting-app-ui
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-ui
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: voting-app-ui
        version: v1
    spec:
      containers:
        - name: voting-app-ui
          image: tedim52/voting-app-ui@latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES
              value: ""
---